//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTest_ShannenValerieTan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int PersonnelId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Surname { get; set; }
        public string ExtensionName { get; set; }
        public int CreatedAt { get; set; }
        public bool Active { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
    }
}
